<?php

use Illuminate\Database\Seeder;

use App\Categoria;


class CategoriasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$types=[
    		"accounting",
		    "airport",
		    "amusement_park",
		    "aquarium",
		    "art_gallery",
		    "atm",
		    "bakery",
		    "bank",
		    "bar",
		    "beauty_salon",
		    "bicycle_store",
		    "book_store",
		    "bowling_alley",
		    "bus_station",
		    "cafe",
		    "campground",
		    "car_dealer",
		    "car_rental",
		    "car_repair",
		    "car_wash",
		    "casino",
		    "cemetery",
		    "church",
		    "city_hall",
		    "clothing_store",
		    "convenience_store",
		    "courthouse",
		    "dentist",
		    "department_store",
		    "doctor",
		    "electrician",
		    "electronics_store",
		    "embassy",
		    "establishment (dejó de estar disponible)",
		    "finance (dejó de estar disponible)",
		    "fire_station",
		    "florist",
		    "food (dejó de estar disponible)",
		    "funeral_home",
		    "furniture_store",
		    "gas_station",
		    "general_contractor (dejó de estar disponible)",
		    "grocery_or_supermarket (dejó de estar disponible)",
		    "gym",
		    "hair_care",
		    "hardware_store",
		    "health (dejó de estar disponible)",
		    "hindu_temple",
		    "home_goods_store",
		    "hospital",
		    "insurance_agency",
		    "jewelry_store",
		    "laundry",
		    "lawyer",
		    "library",
		    "liquor_store",
		    "local_government_office",
		    "locksmith",
		    "lodging",
		    "meal_delivery",
		    "meal_takeaway",
		    "mosque",
		    "movie_rental",
		    "movie_theater",
		    "moving_company",
		    "museum",
		    "night_club",
		    "painter",
		    "park",
		    "parking",
		    "pet_store",
		    "pharmacy",
		    "physiotherapist",
		    "place_of_worship (dejó de estar disponible)",
		    "plumber",
		    "police",
		    "post_office",
		    "real_estate_agency",
		    "restaurant",
		    "roofing_contractor",
		    "rv_park",
		    "school",
		    "shoe_store",
		    "shopping_mall",
		    "spa",
		    "stadium",
		    "storage",
		    "store",
		    "subway_station",
		    "synagogue",
		    "taxi_stand",
		    "train_station",
		    "transit_station",
		    "travel_agency",
		    "university",
		    "veterinary_care",
		    "zoo"
    	];

    	$names = [
    		"contabilidad",
			"Aeropuertos",
			"Parques de atracciones",
			"Acuarios",
			"Galerías de arte",
			"Cajeros automáticos",
			"Panaderías",
			"Bancos",
			"Bares",
			"Salones de belleza",
			"Tiendas de bicicletas",
			"Librerías",
			"Boleras",
			"Estaciones de autobuses",
			"Cafeterías",
			"Terrenos de camping",
			"Vendedores de autos",
			"alquiler de coches",
			"reparación de autos",
			"Lavado de coches",
			"casinos",
			"cementerios",
			"Iglesias",
			"Palacios Municipal",
			"tiendas de ropa",
			"Tiendas de conveniencia",
			"palacios de justicia",
			"dentistas",
			"grandes almacenes",
			"doctores",
			"electricistas",
			"Tiendas de electrónicos",
			"embajadas",
			"Establecimientos (dejó de estar disponible)",
			"Finanzas (dejó de estar disponible)",
			"estaciónes de bomberos",
			"floristas",
			"Comidas (dejó de estar disponible)",
			"Casas funeraria",
			"Tiendas de muebles",
			"gasolineras",
			"General_contractor (dejó de estar disponible)",
			"Grocery_or_supermarket (dejó de estar disponible)",
			"gimnasios",
			"cuidados del cabello",
			"ferreterías",
			"Salud (dejó de estar disponible)",
			"templos hindú",
			"Home_goods_store",
			"hospitalws",
			"agencias de seguros",
			"joyerías",
			"lavanderías",
			"abogados",
			"bibliotecas",
			"Tiendas de licores",
			"Local_government_office",
			"cerrajeros",
			"alojamiento",
			"Entrega de comida",
			"Comida para llevar",
			"mezquitas",
			"Peliculas",
			"cines",
			"empresas de mudanzas",
			"museos",
			"Clubs nocturnos",
			"pintores",
			"parques",
			"estacionamientos",
			"tiendas de mascotas",
			"farmacias",
			"fisioterapeuta",
			"Place_of_worship (dejó de estar disponible)",
			"fontaneros",
			"policía",
			"oficina postal",
			"Real_estate_agency",
			"restaurantes",
			"Contratista de techos",
			"Rv_park",
			"colegios",
			"Tiendas de zapatos",
			"centros comerciales",
			"spas",
			"estadios",
			"almacenamiento",
			"almacenar",
			"estaciónes de metro",
			"sinagogas",
			"paradas de taxi",
			"estaciones de tren",
			"Transit_station",
			"agencias de viajes",
			"Universidades",
			"cuidados veterinarios",
			"Zoologicos"
    	];

    	for ($i=0; $i < count($types) ; $i++) { 
	        factory(Categoria::class)->create(['nombre'=>ucfirst($names[$i]),'categoria'=>$types[$i]]);
    	}
    }
}
